FROM python:3.12-slim

WORKDIR /code

COPY ./ /code

RUN pip install --no-cache-dir --upgrade -r /code/requirements-server.txt

ENV PYTHONPATH "${PYTHONPATH}:/code:/code/app"

# DEVELOPMENT
CMD ["fastapi", "dev", "app/server/main.py", "--port", "8080", "--host", "0.0.0.0"]

# If running behind a proxy like Nginx or Traefik add --proxy-headers
# CMD ["fastapi", "run", "app/main.py", "--port", "80", "--proxy-headers"]
