---

services:
  attu_milvus_ui:
    container_name: attu_milvus_ui
    image: zilliz/attu:latest
    environment:
      HOST_URL: http://localhost:8000 
      MILVUS_URL: milvus-standalone:19530
    ports:
      - 8000:3000

  chat_ui:
    container_name: chat_ui
    env_file:
      - .env
    ports:
      - "8501:8501"
    build:
      context: .
      dockerfile: streamlit/.Dockerfile
    volumes:
      - ./streamlit:/app/streamlit

